name: Deploy to My Local Server

on:
  workflow_dispatch: # workflow_dispatch 表示这个工作流可以手动触发。
  push:
    branches: ['main']


# SSH_PRIVATE_KEY: 本地服务器的私钥
# SSH_USER: 本地服务器的用户名
# SSH_HOST: 本地服务器的 IP 或主机名
# SSH_PORT: 本地服务器的端口（通常是 22）
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: 查看密钥~
      #   run: |
      #     echo "${{secrets.SSH_PRIVATE_KEY}}"
      #     echo "${{secrets.SSH_USER}}"
      #     echo "${{secrets.SSH_HOST}}"
      #     echo "${{secrets.SSH_PORT}}"
      #     ls -al


      - name: Setup SSH
        uses:  ./.github/actions/setup-ssh
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_port: ${{ secrets.SSH_PORT }}

      - name: 安装依赖 && 打包文件
        run: |
          # 在这里添加你的打包命令
          echo "下载依赖...."
          # npm install
          echo "打包文件"
          # npm run build
          echo "显示文件"
          ls -al
          ls -al ~/.ssh
          cat ~/.ssh/config

      # - name: Compress build files
      #   run: |
      #     tar -czvf build.tar.gz -C src . # 打包文件
      #     ssh root "rm -rf /root/affine-pro-build-result" # 清空远程目录
      #     ssh root "mkdir /root/affine-pro-build-result" # 查看远程目录
      #     ssh root "ls /root/affine-pro-build-result -al" # 查看远程目录
      #     scp build.tar.gz root:/root/affine-pro-build-result # 上传文件

      - name: 合并在一起
        run: |
          echo "打包文件"
          tar -czvf build-all.tar.gz ./spec # 打包文件
          echo "清空和查看目录"
          ssh root "rm -rf /root/affine-pro-build-result2 && mkdir /root/affine-pro-build-result2 && ls /root/affine-pro-build-result2 -al"
          echo "查看远程目录"
          ssh root "ls /root/affine-pro-build-result2 -al" # 查看远程目录
          echo "清空和查看目录222"
          ssh root "rm -rf /root/affine-pro-build-result2 && mkdir /root/affine-pro-build-result2 && ls /root/affine-pro-build-result2 -al"
          echo "查看远程目录222"
          ssh root "ls /root/affine-pro-build-result2 -al" # 查看远程目录
          echo "上传文件"
          scp build-all.tar.gz root:/root/affine-pro-build-result2 # 上传文件
          echo "解压缩上传文件"
          ssh root "tar -C /root/affine-pro-build-result2/ -xzvf /root/affine-pro-build-result2/build-all.tar.gz && ls /root/affine-pro-build-result2 -al"
          echo "解压缩上传文件 到指定的目录中"
          ssh root "mkdir -p /root/affine-pro-build-result2/abc && tar -C /root/affine-pro-build-result2/abc -xzvf /root/affine-pro-build-result2/build-all.tar.gz && ls /root/affine-pro-build-result2/abc -al"


      - name: 查看目录结构
        run:
          ls -al

      # - name: 使用 scp 下载文件
      #   run: |
      #     echo "查看线上的文件"
      #     ssh root "ls /root/affine-pro-build-result -al"
      #     echo "查看下载的文件"
      #     mkdir my-test123
      #     scp -r root:/root/affine-pro-build-result ./my-test123
      #     ls ./my-test123 -al

      # - name: 使用 scp 下载文件2
      #   run: |
      #     mkdir my-result
      #     ls -al
      #     scp -r root:/root/affine-pro-build-result ./my-result
      #     echo "查看下载的文件"
      #     ls ./my-result -al

      # - name: Transfer files via SCP
      #   run: |
      #     scp -P ${{ secrets.SSH_PORT }} build.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/affine-pro-build-result

      # - name: Clean up
      #   run: |
      #     rm -rf *
      #     ls -al
