name: "study CI"
on:
  push:
    branches: ["main"]

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: npm --version
      - run: yarn --version
      - run: npm install
      - run: npm run build

  # job2:
  #   runs-on: windows-latest
  #   steps:
  #     - run: node --version

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Run a on-line script
  #       run: echo Hello, world!
  #     - name: Run a multi-line script
  #       run: |
  #         echo Add other action to build,
  #         echo test, and deploy your project
  #     - name: Run node -version
  #       run: node --version
  #     - name: Run python version
  #       run: python --version
  #     - name: Run docker version
  #       run: docker --version
