name: 'study CI'
on:
  push:
    branches: ['main']

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: npm --version
      # 它的作用是将你的仓库代码检出到 GitHub Actions 运行的环境中
      # @v4 是 checkout action 的版本号，表示你正在使用这个 action 的第四个版本。
      # 在 GitHub Actions 中，使用 @ 符号来指定 action 的版本是一种常见的做法。
      # 这段代码的作用是在 GitHub Actions 的运行环境中检出你的仓库代码，以便后续的步骤（例如构建、测试等）可以使用这些代码
      - uses: actions/checkout@v4
      - run: yarn --version
      - run: npm install
      - run: npm run build

  # job2:
  #   runs-on: windows-latest
  #   steps:
  #     - run: node --version

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Run a on-line script
  #       run: echo Hello, world!
  #     - name: Run a multi-line script
  #       run: |
  #         echo Add other action to build,
  #         echo test, and deploy your project
  #     - name: Run node -version
  #       run: node --version
  #     - name: Run python version
  #       run: python --version
  #     - name: Run docker version
  #       run: docker --version
