name: '学习 CI, 并构建镜像推送到 Docker Hub'
on:
  push:
    branches: ['main']

permissions:
  contents: write

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:

      - name: 检索出仓库内容
        uses: actions/checkout@v4

      - name: 显示仓库文件
        run: ls -al

      - name: 显示 yarn 版本
        run: yarn --version

      # - name: 安装依赖 && 打包文件
      #   run: |
      #     yarn install
      #     yarn build

      - name: 登录 DockerHub
        uses: docker/login-action@v3
        width:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      - name: 构建并推送到 Docker Hub
        uses: docker/build-push-action@v5
        width:
          push: true
          tags: feifei6213/express-ts:latest